name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            echo "[INFO] Login success. Pulling Docker image..."
            mkdir -p ~/kelompok13 && cd ~/kelompok13

            echo "[INFO] Writing docker-compose.yml..."
            cat <<EOF > docker-compose.yml
            version: '3'
            services:
              app:
                image: viexxx/kelompok13:latest
                ports:
                  - "80:3000"
                restart: always
            EOF

            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull viexxx/kelompok13:latest

            echo "[INFO] Restarting container..."
            docker-compose down || true
            docker-compose up -d
