name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - testing7

jobs:
  deploy:
    name: Deploy Docker App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2INSTANCEPUBLICDNS }}
          username: ubuntu
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: |
            echo "[INFO] Login success. Pulling Docker image..."
            cd ~/kelompok13 || mkdir -p ~/kelompok13 && cd ~/kelompok13

            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull viexxx/kelompok13:latest

            echo "[INFO] Restarting container..."
            docker-compose down || true
            docker-compose up -d
