name: Continuous Deployment

on:
  push:
    branches:
      - testing2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Pull Docker Image
        # Pastikan ini menarik image dengan SHA yang sama dengan yang dibangun dan diuji di CI
        run: docker pull viexxx/kelompok13:${{ github.sha }}

      - name: Deploy to EC2
        run: |
          # Simpan kunci SSH privat ke file temporer
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > PSO B Kelompok 13.pem
          # Atur izin yang benar untuk kunci SSH
          chmod 400 PSO B Kelompok 13.pem
          # Koneksi SSH ke instance EC2 dan jalankan perintah Docker
          ssh -o StrictHostKeyChecking=no -i PSO B Kelompok 13.pem ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
            # Tarik image Docker terbaru
            docker pull viexxx/kelompok13:${{ github.sha }}
            # Hapus kontainer yang ada jika ada
            docker rm -f pso-b-kelompok13-container || true
            # Jalankan kontainer Docker baru
            docker run -d -p 3000:3000 --name pso-b-kelompok13-container viexxx/kelompok13:${{ github.sha }}
          EOF