name: Continuous Deployment - Azure VM

on:
  push:
    branches:
      - dev-ridho  # ganti sesuai branch untuk Azure

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker Image
        run: docker pull viexxx/kelompok13:latest

      - name: Upload Azure SSH Key
        run: |
          echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > tasktracker_key.pem
          chmod 400 tasktracker_key.pem
          chmod 600 tasktracker_key.pem

      - name: Print Azure VM Public IP
        run: echo "${{ secrets.AZURE_VM_PUBLIC_IP }}"

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i tasktracker_key.pem ubuntu@${{ secrets.AZURE_VM_PUBLIC_IP }} << 'EOF'
            docker pull viexxx/kelompok13:latest
            docker rm -f devops-azure-container || true
            docker run -d -p 3000:3000 --name devops-azure-container viexxx/kelompok13
          EOF
