name: Continuous Deployment

on:
  push:
    branches:
      - testing4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract deploy files (contains PEM key)
        run: |
          tar -xf deploy_files.tar
          chmod 400 pso_b_kelompok_13.pem

      - name: Pull Docker Image from Docker Hub
        run: docker pull viexxx/kelompok13:latest

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i pso_b_kelompok_13.pem ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
            docker pull viexxx/kelompok13:latest
            docker rm -f devops-pso-container || true
            docker run -d -p 3000:3000 --name devops-pso-container viexxx/kelompok13
          EOF
