name: Continuous Deployment

on:
  push:
    branches:
      - testing2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Pull Docker Image
        run: docker pull viexxx/kelompok13:latest

      - name: Upload SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > pso_b_kelompok_13.pem
          chmod 400 "pso_b_kelompok_13.pem"
          chmod 600 "pso_b_kelompok_13.pem"
          
      - name: Print EC2 instance DNS
        run: echo "${{ secrets.EC2_INSTANCE_PUBLIC_DNS }}"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key-pair-pso_b_kelompok_13.pem ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
            docker pull viexxx/kelompok13:latest
            docker rm -f devops-pso-container || true
            docker run -d -p 3000:3000 --name devops-pso-container viexxx/kelompok13
          EOF