name: Initial configuration
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t viexxx/kelompok13 .

      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish image to docker hub
        run: docker push viexxx/kelompok13:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull image from docker hub
        run: docker pull viexxx/kelompok13:latest

      - name: Run vitest testing
        run: |
          docker run --rm viexxx/kelompok13:latest sh -c "npm install && npm test"
