name: Infrastructure Provisioning

on:
  push:
    branches:
      - testing6 #a

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ap-southeast-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          AWSACCESSKEY: ${{ secrets.AWSACCESSKEY }}
          AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWSACCESSKEY: ${{ secrets.AWSACCESSKEY }}
          AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}